name: Website

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  #print the event payload to the log
  print-event:
    runs-on: ubuntu-latest
    steps:
      - run: echo "github.event.workflow_run.event ${{ toJson(github.event.workflow_run.event) }}"
      - run: echo "github.event.workflow_run.head_commit.message ${{ toJson(github.event.workflow_run.head_commit.message) }}"
      - run: echo "github.ref ${{ toJson(github.ref) }}"
  check-workflow-status:
    if: ${{ (github.event.workflow_run.event == 'push' && (github.ref == 'main' || contains(github.event.workflow_run.head_commit.message, 'changeset-release/main'))) }}
    runs-on: ubuntu-latest
    steps:
      - name: Verify Release status
        run: |
          workflow_status=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }} | jq -r .conclusion)
          if [ "$workflow_status" != "success" ]; then
            echo "Release failed, not deploying"
            exit 1
          fi
  build_site:
    needs: check-workflow-status
    permissions:
      pages: write
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        env:
          BASE_PATH: "/${{ github.event.repository.name }}"
        run: pnpm build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          # this should match the `pages` option in your adapter-static options
          path: "apps/website/build/"
  deploy:
    name: Deploy
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
