name: Website

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  check-workflow-status:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Release status
        run: |
          workflow_status=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }} | jq -r .conclusion)
          if [ "$workflow_status" != "success" ]; then
            echo "Release failed, not deploying"
            exit 1
          fi
  build_site:
    needs: check-workflow-status
    permissions:
      pages: write
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if changeset includes a release for website
        id: check_release
        run: |
          CHANGESET=$(git diff --name-only HEAD~1 HEAD)
          if echo "$CHANGESET" | grep -q "^apps/website/"; then
            echo "::set-output name=release::true"
          else
            echo "::set-output name=release::false"
          fi

      - name: Check if PR comes from changeset and includes 'changeset-release/main'
        id: check_changeset
        run: |
          PR_TITLE=$(gh pr view https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }} --json title -q ".title")
          if [[ "$PR_TITLE" == *"changeset-release/main"* ]]; then
            echo "::set-output name=changeset::true"
          else
            echo "::set-output name=changeset::false"
          fi

      - name: Stop job if no release or not a changeset
        run: |
          if [[ "${{ steps.check_release.outputs.release }}" != 'true' || "${{ steps.check_changeset.outputs.changeset }}" != 'true' ]]; then
            echo "No release for website or not a changeset, stopping job."
            echo "::stop-commands::"
          fi

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        env:
          BASE_PATH: "/${{ github.event.repository.name }}"
        run: pnpm build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          # this should match the `pages` option in your adapter-static options
          path: "apps/website/build/"
  deploy:
    name: Deploy
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
